### PR TITLE
Fix previous milestones section

### PR DESCRIPTION
**Pull request by dobbymoodge**

### CODE REVIEW

**Comment by danmcp** [comment]
Fix the commit message.

**Comment by danmcp** [comment]
@dobbymoodge Can you take a look at the travis tests failing.

**Comment by dobbymoodge** [comment]
@danmcp current activesupport doesn't support ruby 2.0 any longer. I'll look at locking in a working version

**Comment by dobbymoodge** [comment]
That is, doesn't support Ruby < 2.2

**Pull request merged**
